### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by Fux002** [scoofy/xbrl-to-json#1]
Hi,

Hi! Can this be used for a form 4 or form 3 filing aswell.

If not do you have an alternative and is it complicated to amend to allow this?

Thx a lot,

**Comment by scoofy** [comment]
I'm not sure, i'd also not suggest using it yet (it's currently incomplete). I'm almost done, but when i'm done it should work for most form types. The data structure is odd, and i'm only working on converting the last calculation type files.

Generally speaking though, i think it will work for those form, when it's done?

**Comment by scoofy** [comment]
FYI, i've fixed almost all the previous issues i missed before... the program should download and convert much better now

**Comment by scoofy** [comment]
Okay, after reviewing this issue further, it seems that Form 4 is published in HTML, not XBRL, thus this program wouldn't be relevant to that.
